"""
core/llm/function_call_handler.py
=================================
Executes tool calls generated by Ollama function calling.
"""

from typing import Any
from core.tools.tool_registry import tool_registry


class FunctionCallHandler:
    """
    Parses and dispatches tool calls from LLM responses.
    """

    def handle_tool_call(self, tool_call: dict[str, Any]) -> dict[str, Any]:
        """
        Executes a single tool call.

        Args:
            tool_call: A dictionary representing the tool call, structured as:
                {
                    "function": {
                        "name": "tool_name",
                        "arguments": { ... }
                    }
                }

        Returns:
            The tool execution result dict (with 'success', 'result', and 'error').
        """
        function_info = tool_call.get("function", {})
        name = function_info.get("name")
        arguments = function_info.get("arguments", {})

        # Execute using the global tool registry
        return tool_registry.execute(name, arguments)


# Singleton handler
function_call_handler = FunctionCallHandler()
